using generic command

diff --git a/scripts/g810_switch_profile b/scripts/g810_switch_profile
--- a/scripts/g810_switch_profile
+++ b/scripts/g810_switch_profile
@@ -5,18 +5,16 @@
 #    or: g810_switch_profile (no argument & we'll get a menu)
 # Fill the myModelName variable with your supported keyboard.
 # G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro,
-# and the myModelBinary in lower case suffixed with '-led'
 # use lsusb to find out your model name & model id
 
 myModelName=G815
 myModelId=c33f
-myModelBinary=g815-led
 
 ! grep -q "$myModelName" < <(lsusb) && {
 
-    [[ -z $(command -v $myModelBinary) ]] && {
-    	echo " $myModelBinary not found...exiting"
-    	exit 127
+    [[ -z $(command -v g810-led) ]] && {
+        echo " g810-led not found...exiting"
+        exit 127
     }
 
     echo "$myModelName is not plugged in, exiting..."
@@ -33,7 +31,7 @@ profile_name="$1"
 
 if [[ -f profile_$1 ]]; then
 
-    "$myModelBinary" -pp < profile_"$profile_name"
+    g810-led -pp < profile_"$profile_name"
     sudo sed -i "s/${profile}/profile_${profile_name}/" "$rules"
 	
 elif [[ ! -f profile_$1 ]]; then
@@ -59,7 +57,7 @@ elif [[ ! -f profile_$1 ]]; then
 			| sed 's,.*/,,;s/profile_//'
 		); do
 
-	    "$myModelBinary" -pp < profile_"$name"
+	    g810-led -pp < profile_"$name"
 	    sudo sed -i "s/${profile}/profile_${name}/" \
 	    "$rules"
 		echo " profile $name selected."
