added american english profiles

diff --git a/scripts/g810_delete_profile b/scripts/g810_delete_profile
--- a/scripts/g810_delete_profile
+++ b/scripts/g810_delete_profile
@@ -1,81 +1,54 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # Author: Barret E <https://github.com/archusXIV>
 # Usage: g810_delete_profile <profile_name>
 #    or: g810_delete_profile (no argument & we'll get a menu)
-# Fill the myModelName variable with your supported keyboard.
-# G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro,
-# use lsusb to find out your model name & model id
+# supported keyboard: G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro
 
-myModelName=G815
-myModelId=c33f
+# shellcheck disable=SC2024
+myModelName=$(awk '/Keyboard/{print $9}' < <(lsusb))
+myModelBinary="${myModelName,}-led"
 
 ! grep -q "$myModelName" < <(lsusb) && {
-
-    [[ -z $(command -v g810-led) ]] && {
-        echo " g810-led not found...exiting"
+    [[ -z $(command -v "$myModelBinary") ]] && {
+        echo " No g810-led related binary found...exiting"
         exit 127
     }
-
     echo "$myModelName is not plugged in, exiting..."
     exit 1
-    
 }
 
-etcProfiles="/etc/g810-led/profiles"
-cd "$etcProfiles" || exit 1
-
-config_dir="$HOME/.config/g810-led/profiles"
-rules="/etc/udev/rules.d/g810-led.rules"
-profile=$(grep -e "$myModelId" "$rules" | sed 's,.*/,,;s/"//')
+etc_confdir="/etc/g810-led"
+config_profiles="$HOME/.config/g810-led/profiles"
+profile=$(sed -n '1s/# //p' "$etc_confdir"/profile)
+cd "$etc_confdir/profiles" || exit 1
 
 if [[ $1 = default ]]; then
-    echo "You cannot delete $1 profile..." && exit 0
-elif [[ profile_$1 = "$profile" ]]; then
-
-    g810-led -pp < profile_default
-    sudo sed -i "s/${profile}/profile_default/" "$rules"
-    sudo rm profile_"$1"
-    rm "$config_dir"/profile_"$1"
-	echo " profile $1 deleted."
-    
-elif [[ profile_$1 != "$profile" ]]; then
-
-	[[ -z $1 ]] && echo -e " no argument given...\n" || \
-	echo -e " $1 does not exist.\n"
-
-	awk -v ID="$myModelId" -v PFL="$profile" '
-		$0~ID{
-			gsub("/","")
-			sub("[\"]","")
-			}
-		{ print " in use: "PFL" "; exit }
-	' "$rules" | sed 's/profile_//'
-	printf '\n'
-
-	PS3=""$'\n'" Choose a RGB profile to delete: "
-    select name in $(
-            find . \
-            -type f \
-            -not -name "profile_default" \
-            -name "profile_*" \
-	        | sort \
-            | sed 's,.*/,,;s/profile_//'
-        ); do
-
-        if [[ profile_$name = "$profile" ]]; then
-
-	        g810-led -pp < profile_default
-            sudo sed -i "s/${profile}/profile_default/" "$rules"
-            sudo rm profile_"$name"
-            rm "$config_dir"/profile_"$name"
-		    echo " profile $name deleted."
+    echo "You cannot delete default profile..." && exit 1
+elif [[ $1 = "$profile" ]]; then
+    profile_name="$1"
+    sudo "$myModelBinary" -pp < default
+    sudo cp -f default "$etc_confdir"/profile
+    sudo rm "$profile_name"
+    rm "$config_profiles/$profile_name"
+    echo " profile $1 deleted."
+elif [[ $1 != "$profile" ]]; then
+    [[ -z $1 ]] && echo -e " no argument given...\n" || \
+    echo -e " $1 does not exist.\n"
+    printf '\n'
+    PS3=""$'\n'" Choose a RGB profile to delete: "
+    select profile_name in $(find . -type f -not -name "default" -printf '%f\n' | sort); do
+        if [[ $profile_name == "$profile" ]]; then
+            sudo "$myModelBinary" -pp < default
+            sudo cp -f default "$etc_confdir"/profile
+            sudo rm "$profile_name"
+            rm "$config_profiles/$profile_name"
+            echo " profile $profile_name deleted."
         else
-            sudo rm profile_"$name"
-            rm "$config_dir"/profile_"$name"
-		    echo " profile $name deleted."
+            sudo rm "$profile_name"
+            rm "$config_profiles/$profile_name"
+            echo " profile $profile_name deleted."
         fi
-        
         break
     done
 fi
