Added changes in all scripts

diff --git a/scripts/g810_delete_profile b/scripts/g810_delete_profile
--- a/scripts/g810_delete_profile
+++ b/scripts/g810_delete_profile
@@ -1,21 +1,34 @@
 #!/usr/bin/env bash
 
 # Author: Barret E <https://github.com/archusXIV>
+#
+# This script let us delete RGB profiles designed to be use with our
+# Logitech compatible keyboard.
+# First install the g810-led package from sources or the AUR repository.
+# Supported keyboards: G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro
+# use lsusb | grep -i keyboard, to find out your model name & model id
 # Usage: g810_delete_profile <profile_name>
 #    or: g810_delete_profile (no argument & we'll get a menu)
-# supported keyboard: G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro
 
 # shellcheck disable=SC2024
-myModelName=$(awk '/Keyboard/{print $9}' < <(lsusb))
-myModelBinary="${myModelName,}-led"
-
-! grep -q "$myModelName" < <(lsusb) && {
-    [[ -z $(command -v "$myModelBinary") ]] && {
-        printf '%s\n' " No g810-led related binary found...exiting"
-        exit 127
-    }
-    printf '%s\n' "$myModelName is not plugged in, exiting..."
+[[ ! $(awk '/Keyboard/{print $7}' < <(lsusb)) =~ ^Logitech,$ ]] && {
+    printf '%s\n' " ${R}No Logitech keyboard detected, exiting...${Z}"
     exit 1
+}
+
+declare -a Keyboards=( G213 G410 G413 G512 G513 G610 G810 G815 G910 Gpro )
+for keyboard in "${Keyboards[@]}"; do
+    if [[ $(awk '/Keyboard/{print $9}' < <(lsusb)) != "$keyboard" ]]; then
+        continue
+    else
+        myModelName="$keyboard"
+    fi
+done
+
+myModelBinary="${myModelName,}-led"
+command -v "$myModelBinary" || {
+    printf '%s\n' " ${R}No g810-led related binary found...exiting${Z}"
+    exit 127
 }
 
 etc_confdir="/etc/g810-led"
@@ -24,17 +37,17 @@ profile=$(sed -n '1s/# //p' "$etc_confdir"/profile)
 cd "$etc_confdir/profiles" || exit 1
 
 if [[ $1 = default ]]; then
-    printf '%s\n' "You cannot delete default profile..." && exit 1
+    echo "You cannot delete default profile..." && exit 1
 elif [[ $1 = "$profile" ]]; then
     profile_name="$1"
     sudo "$myModelBinary" -pp < default
     sudo cp -f default "$etc_confdir"/profile
     sudo rm "$profile_name"
     rm "$config_profiles/$profile_name"
-    printf '%s\n' " profile $1 deleted."
+    echo " profile $1 deleted."
 elif [[ $1 != "$profile" ]]; then
-    [[ -z $1 ]] && printf '%s\n' " no argument given..." || \
-    printf '%s\n' " $1 does not exist."
+    [[ -z $1 ]] && echo -e " no argument given...\n" || \
+    echo -e " $1 does not exist.\n"
     printf '\n'
     PS3=""$'\n'" Choose a RGB profile to delete: "
     select profile_name in $(find . -type f -not -name "default" -printf '%f\n' | sort); do
@@ -43,11 +56,11 @@ elif [[ $1 != "$profile" ]]; then
             sudo cp -f default "$etc_confdir"/profile
             sudo rm "$profile_name"
             rm "$config_profiles/$profile_name"
-            printf '%s\n' " profile $profile_name deleted."
+            echo " profile $profile_name deleted."
         else
             sudo rm "$profile_name"
             rm "$config_profiles/$profile_name"
-            printf '%s\n' " profile $profile_name deleted."
+            echo " profile $profile_name deleted."
         fi
         break
     done
